# Generated by Django 5.2.5 on 2025-09-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapterLike',
        ),
    ]
