# Generated by Django 5.2.5 on 2025-10-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0005_chapterview'),
        ('manga_section', '0010_alter_chapter_ch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterview',
            name='manga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manga_section.manga'),
            preserve_default=False,
        ),
    ]
