# Generated by Django 5.2.5 on 2025-10-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0006_chapterview_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterview',
            name='view_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
