# Generated by Django 5.2.5 on 2026-01-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0007_chapterview_view_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewed_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
