# Generated by Django 5.2.5 on 2026-01-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0008_profile_viewed_tutorial'),
        ('manga_section', '0016_alter_staff_link_for_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlike',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_section.manga'),
        ),
    ]
