# Generated by Django 5.2.1 on 2026-02-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0009_chapterlike_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewed_double',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='viewed_single',
            field=models.BooleanField(default=False),
        ),
    ]
