# Generated by Django 5.2.1 on 2026-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0012_alter_profile_reader_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reader_mode',
            field=models.CharField(choices=[('left_to_right', 'Слева направо'), ('right_to_left', 'Справа налево')], default='left_to_right'),
        ),
    ]
