# Generated by Django 5.2.1 on 2026-07-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0013_alter_profile_reader_mode'),
        ('manga_section', '0020_chapter_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapterview',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_views', to='manga_section.manga'),
        ),
    ]
