# Generated by Django 5.2.6 on 2025-09-10 04:23

import django.db.models.deletion
import manga_section.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, unique=True, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_number', models.PositiveIntegerField(verbose_name='Номер')),
                ('ch_name', models.CharField(max_length=100, verbose_name='Название')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=25, unique=True, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Номер страницы')),
                ('page_image', models.ImageField(upload_to=manga_section.models.chapter_image_path, verbose_name='Страница')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manga_section.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_name', models.CharField(max_length=150, verbose_name='Название')),
                ('manga_slug', models.SlugField(max_length=200, unique=True, verbose_name='SLUG-адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('authors', models.ManyToManyField(to='manga_section.author', verbose_name='Автор')),
                ('genres', models.ManyToManyField(to='manga_section.genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_number', models.PositiveIntegerField(verbose_name='Номер тома')),
                ('vol_cover', models.ImageField(upload_to=manga_section.models.volume_cover_path)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='manga_section.manga', verbose_name='Манга')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga_section.volume', verbose_name='Манга'),
        ),
    ]
