# Generated by Django 5.2.6 on 2025-09-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterimage',
            old_name='page_img',
            new_name='page_image',
        ),
        migrations.RenameField(
            model_name='chapterimage',
            old_name='page_num',
            new_name='page_number',
        ),
    ]
