# Generated by Django 5.2.5 on 2025-09-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
