# Generated by Django 5.2.6 on 2025-09-09 15:57

import manga_section.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0002_rename_page_img_chapterimage_page_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterimage',
            name='page_image',
            field=models.ImageField(upload_to=manga_section.models.chapter_image_path, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.ImageField(upload_to=manga_section.models.manga_cover_path, verbose_name='Обложка'),
        ),
    ]
