# Generated by Django 5.2.5 on 2025-09-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0002_chapter_dislike_count_chapter_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='like_count',
        ),
    ]
