# Generated by Django 5.2.5 on 2025-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0003_remove_chapter_dislike_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist_name', models.CharField(max_length=50)),
                ('link_for_offers', models.URLField(max_length=250, verbose_name='Ссылка для связи')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='editor',
            field=models.ManyToManyField(related_name='editors', to='manga_section.staff', verbose_name='Редактор'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='interpreter',
            field=models.ManyToManyField(related_name='interpreters', to='manga_section.staff', verbose_name='Переводчик'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='retoucher',
            field=models.ManyToManyField(related_name='retouchers', to='manga_section.staff', verbose_name='Ретушёр'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='sfx_artist',
            field=models.ManyToManyField(related_name='sfx_artists', to='manga_section.staff', verbose_name='Художник по звукам'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='typesetter',
            field=models.ManyToManyField(related_name='typesetters', to='manga_section.staff', verbose_name='Верстальщик'),
        ),
    ]
