# Generated by Django 5.2.5 on 2025-09-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0004_staff_chapter_editor_chapter_interpreter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='assist_name',
            new_name='staff_name',
        ),
    ]
