# Generated by Django 5.2.5 on 2025-09-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0005_rename_assist_name_staff_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='editor',
            field=models.ManyToManyField(default=None, related_name='editors', to='manga_section.staff', verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='interpreter',
            field=models.ManyToManyField(default=None, related_name='interpreters', to='manga_section.staff', verbose_name='Переводчик'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='retoucher',
            field=models.ManyToManyField(default=None, related_name='retouchers', to='manga_section.staff', verbose_name='Ретушёр'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='sfx_artist',
            field=models.ManyToManyField(default=None, related_name='sfx_artists', to='manga_section.staff', verbose_name='Художник по звукам'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='typesetter',
            field=models.ManyToManyField(default=None, related_name='typesetters', to='manga_section.staff', verbose_name='Верстальщик'),
        ),
    ]
