# Generated by Django 5.2.5 on 2025-09-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0006_alter_chapter_editor_alter_chapter_interpreter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='editor',
            field=models.ManyToManyField(blank=True, default=None, related_name='editors', to='manga_section.staff', verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='retoucher',
            field=models.ManyToManyField(blank=True, default=None, related_name='retouchers', to='manga_section.staff', verbose_name='Ретушёр'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='sfx_artist',
            field=models.ManyToManyField(blank=True, default=None, related_name='sfx_artists', to='manga_section.staff', verbose_name='Художник по звукам'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='typesetter',
            field=models.ManyToManyField(blank=True, default=None, related_name='typesetters', to='manga_section.staff', verbose_name='Верстальщик'),
        ),
    ]
