# Generated by Django 5.2.5 on 2025-09-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0007_alter_chapter_editor_alter_chapter_retoucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='interpreter',
            field=models.ManyToManyField(blank=True, default=None, related_name='interpreters', to='manga_section.staff', verbose_name='Переводчик'),
        ),
    ]
