# Generated by Django 5.2.5 on 2025-09-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0008_alter_chapter_interpreter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterimage',
            name='is_double_page',
            field=models.BooleanField(default=False),
        ),
    ]
