# Generated by Django 5.2.5 on 2025-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0009_chapterimage_is_double_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='ch_number',
            field=models.FloatField(verbose_name='Номер'),
        ),
    ]
