# Generated by Django 5.2.5 on 2025-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0010_alter_chapter_ch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterimage',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
