# Generated by Django 5.2.5 on 2025-12-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0011_chapterimage_is_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
