# Generated by Django 5.2.5 on 2025-12-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0013_chapterimage_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterimage',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Ширина страницы'),
        ),
    ]
