# Generated by Django 5.2.5 on 2025-12-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0014_alter_chapterimage_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterimage',
            name='width',
        ),
    ]
