# Generated by Django 5.2.5 on 2026-01-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0015_remove_chapterimage_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='link_for_offers',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка для связи'),
        ),
    ]
