# Generated by Django 5.2.1 on 2026-05-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='artists',
            field=models.ManyToManyField(related_name='manga_as_artist', to='manga_section.author', verbose_name='Художник'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='authors',
            field=models.ManyToManyField(related_name='manga_as_author', to='manga_section.author', verbose_name='Автор'),
        ),
    ]
