# Generated by Django 5.2.1 on 2026-06-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0018_manga_artists_alter_manga_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manga_section.comment', verbose_name='Родитель'),
        ),
    ]
