# Generated by Django 5.2.1 on 2026-06-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_section', '0019_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
