# Generated by Django 5.2.6 on 2025-09-08 17:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, verbose_name='Название')),
                ('post_slug', models.SlugField(max_length=200, unique=True, verbose_name='SLUG-адрес')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Счётчик просмотров')),
            ],
        ),
    ]
