# Generated by Django 5.2.6 on 2025-09-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Счётчик просмотров'),
        ),
    ]
