# Generated by Django 5.2.5 on 2025-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Отображение на сайте'),
        ),
    ]
