# Generated by Django 5.2.5 on 2025-09-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0002_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Отображение на главной'),
        ),
    ]
