# Generated by Django 5.2.5 on 2025-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0004_messagefaq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagefaq',
            options={'verbose_name': 'Предложения', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AddField(
            model_name='messagefaq',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
