# Generated by Django 5.2.1 on 2026-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0008_postcomment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='parent_comment',
            field=models.ManyToManyField(to='post_section.postcomment', verbose_name='Родитель'),
        ),
    ]
