# Generated by Django 5.2.1 on 2026-05-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0010_alter_postcomment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post_section.thread', verbose_name='Ветка'),
        ),
    ]
