# Generated by Django 5.2.1 on 2026-05-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0011_alter_postcomment_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='parent_comment',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='post_section.postcomment', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post_section.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='thread',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post_section.thread', verbose_name='Ветка'),
        ),
    ]
