# Generated by Django 5.2.1 on 2026-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0012_alter_postcomment_parent_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='parent_comment',
            field=models.ManyToManyField(blank=True, default=None, to='post_section.postcomment', verbose_name='Родитель'),
        ),
    ]
